// Generated by CoffeeScript 1.4.0
(function() {

  console.log("this is state");

  console.log(chrome.extension.getViews());

  console.log(chrome.extension.getBackgroundPage());

  window.state = true;

  window.wpm = 300;

  window.wph = 3;

  chrome.extension.onRequest.addListener(function(request, sender, sendResponse) {
    console.log(request);
    console.log(sender);
    console.log(sendResponse);
    if (request.action === 'getState') {
      return sendResponse({
        state: window.state
      });
    } else if (request.action === 'setState') {
      window.state = request.state;
      return sendResponse({});
    } else if (request.action === 'getWPM') {
      return sendResponse({
        wpm: window.wpm
      });
    } else if (request.action === 'setWPM') {
      window.wpm = request.wpm;
      return sendResponse({});
    } else if (request.action === 'getWPH') {
      return sendResponse({
        wph: window.wph
      });
    } else if (request.action === 'setWPH') {
      window.wph = request.wph;
      return sendResponse({});
    }
  });

}).call(this);
