// Generated by CoffeeScript 1.4.0
(function() {
  var _this = this;

  this.state = true;

  this.wpm = 300;

  this.wph = 3;

  this.messageCurrentTab = function(message) {
    return chrome.tabs.query({
      currentWindow: true,
      active: true
    }, function(tabArray) {
      console.log(tabArray);
      return chrome.tabs.sendMessage(tabArray[0].id, message, function() {});
    });
  };

  chrome.extension.onRequest.addListener(function(request, sender, sendResponse) {
    console.log(request);
    if (request.action === 'getState') {
      return sendResponse({
        state: _this.state
      });
    } else if (request.action === 'setState') {
      _this.state = request.state;
      _this.messageCurrentTab({
        action: 'setState',
        state: window.state
      });
      return sendResponse({});
    } else if (request.action === 'getWPM') {
      return sendResponse({
        wpm: _this.wpm
      });
    } else if (request.action === 'setWPM') {
      _this.wpm = request.wpm;
      _this.messageCurrentTab({
        action: 'setWPM',
        wpm: window.wpm
      });
      return sendResponse({});
    } else if (request.action === 'getWPH') {
      return sendResponse({
        wph: _this.wph
      });
    } else if (request.action === 'setWPH') {
      _this.wph = request.wph;
      _this.messageCurrentTab({
        action: 'setWPH',
        wph: window.wph
      });
      return sendResponse({});
    }
  });

}).call(this);
