(function() {function f(a){throw a;}var i=void 0,k=!0,m=null,n=!1;function o(a){return function(){return this[a]}}function p(a){return function(){return a}}var s,t=this;function aa(){}
function ba(a){var b=typeof a;if("object"==b)if(a){if(a instanceof Array)return"array";if(a instanceof Object)return b;var c=Object.prototype.toString.call(a);if("[object Window]"==c)return"object";if("[object Array]"==c||"number"==typeof a.length&&"undefined"!=typeof a.splice&&"undefined"!=typeof a.propertyIsEnumerable&&!a.propertyIsEnumerable("splice"))return"array";if("[object Function]"==c||"undefined"!=typeof a.call&&"undefined"!=typeof a.propertyIsEnumerable&&!a.propertyIsEnumerable("call"))return"function"}else return"null";
else if("function"==b&&"undefined"==typeof a.call)return"object";return b}function x(a){return a!==i}function ca(a){var b=ba(a);return"array"==b||"object"==b&&"number"==typeof a.length}function y(a){return"string"==typeof a}function da(a){return"number"==typeof a}function ea(a){var b=typeof a;return"object"==b&&a!=m||"function"==b}Math.floor(2147483648*Math.random()).toString(36);function fa(a,b,c){return a.call.apply(a.bind,arguments)}
function ga(a,b,c){a||f(Error());if(2<arguments.length){var d=Array.prototype.slice.call(arguments,2);return function(){var c=Array.prototype.slice.call(arguments);Array.prototype.unshift.apply(c,d);return a.apply(b,c)}}return function(){return a.apply(b,arguments)}}function z(a,b,c){z=Function.prototype.bind&&-1!=Function.prototype.bind.toString().indexOf("native code")?fa:ga;return z.apply(m,arguments)}function ha(a,b){function c(){}c.prototype=b.prototype;a.Qc=b.prototype;a.prototype=new c};function ia(a){a=String(a);if(/^\s*$/.test(a)?0:/^[\],:{}\s\u2028\u2029]*$/.test(a.replace(/\\["\\\/bfnrtu]/g,"@").replace(/"[^"\\\n\r\u2028\u2029\x00-\x08\x10-\x1f\x80-\x9f]*"|true|false|null|-?\d+(?:\.\d*)?(?:[eE][+\-]?\d+)?/g,"]").replace(/(?:^|:|,)(?:[\s\u2028\u2029]*\[)+/g,"")))try{return eval("("+a+")")}catch(b){}f(Error("Invalid JSON string: "+a))}function ja(){this.rb=i}
function ka(a,b,c){switch(typeof b){case "string":la(b,c);break;case "number":c.push(isFinite(b)&&!isNaN(b)?b:"null");break;case "boolean":c.push(b);break;case "undefined":c.push("null");break;case "object":if(b==m){c.push("null");break}if("array"==ba(b)){var d=b.length;c.push("[");for(var e="",g=0;g<d;g++)c.push(e),e=b[g],ka(a,a.rb?a.rb.call(b,String(g),e):e,c),e=",";c.push("]");break}c.push("{");d="";for(g in b)Object.prototype.hasOwnProperty.call(b,g)&&(e=b[g],"function"!=typeof e&&(c.push(d),
la(g,c),c.push(":"),ka(a,a.rb?a.rb.call(b,g,e):e,c),d=","));c.push("}");break;case "function":break;default:f(Error("Unknown type: "+typeof b))}}var ma={'"':'\\"',"\\":"\\\\","/":"\\/","\b":"\\b","\f":"\\f","\n":"\\n","\r":"\\r","\t":"\\t","\x0B":"\\u000b"},na=/\uffff/.test("\uffff")?/[\\\"\x00-\x1f\x7f-\uffff]/g:/[\\\"\x00-\x1f\x7f-\xff]/g;
function la(a,b){b.push('"',a.replace(na,function(a){if(a in ma)return ma[a];var b=a.charCodeAt(0),e="\\u";16>b?e+="000":256>b?e+="00":4096>b&&(e+="0");return ma[a]=e+b.toString(16)}),'"')};function oa(a){if("undefined"!==typeof JSON&&x(JSON.stringify))a=JSON.stringify(a);else{var b=[];ka(new ja,a,b);a=b.join("")}return a};function A(a,b,c,d){var e;d<b?e="at least "+b:d>c&&(e=0===c?"none":"no more than "+c);e&&f(Error(a+" failed: Was called with "+d+(1===d?" argument.":" arguments.")+" Expects "+e+"."))}
function C(a,b,c){var d="";switch(b){case 1:d=c?"first":"First";break;case 2:d=c?"second":"Second";break;case 3:d=c?"third":"Third";break;case 4:d=c?"fourth":"Fourth";break;default:pa.assert(n,"errorPrefix_ called with argumentNumber > 4.  Need to update it?")}a+=" failed: ";c&&(a+="If provided, ");return a+(d+" argument ")}function D(a,b,c,d){(!d||x(c))&&"function"!=ba(c)&&f(Error(C(a,b,d)+"must be a valid function."))};var qa={},pa={},ra=/[\[\].#$\/]/,sa=/[\[\].#$]/;function ta(a){return y(a)&&0!==a.length&&!ra.test(a)}function ua(a,b,c){(!c||x(b))&&va(C(a,1,c),b)}
function va(a,b,c){c||(c=0);x(b)||f(Error(a+"contains undefined."));"function"==ba(b)&&f(Error(a+"contains a function."));da(b)&&(b!=b||b==Number.POSITIVE_INFINITY||b==Number.NEGATIVE_INFINITY)&&f(Error(a+"contains "+b.toString()));1E3<c&&f(new TypeError(a+"contains a cyclic object value."));y(b)&&(b.length>10485760/3&&10485760<qa.Rc.Pc(b).length)&&f(Error(a+"contains a string greater than 10485760 utf8 bytes ('"+b.substring(0,50)+"...')"));if(ea(b))for(var d in b)b.hasOwnProperty(d)&&(".priority"!==
d&&(".value"!==d&&!ta(d))&&f(Error(a+"contains an invalid key ("+d+').  Keys must be non-empty strings and can\'t contain ".", "#", "$", "/", "[", or "]"')),va(a,b[d],c+1))}function wa(a,b,c,d){(!d||x(c))&&(c!==m&&!da(c)&&!y(c))&&f(Error(C(a,b,d)+"must be a valid firebase priority (null or a string.)"))}
function xa(a,b,c){if(!c||x(b))switch(b){case "value":case "child_added":case "child_removed":case "child_changed":case "child_moved":break;default:f(Error(C(a,1,c)+'must be a valid event type: "value", "child_added", "child_removed", "child_changed", or "child_moved".'))}}function za(a,b){x(b)&&!ta(b)&&f(Error(C(a,2,k)+'must be a valid firebase key (non-empty string, not containing ".", "#", "$", "/", "[", or "]").'))}
function Aa(a,b){(!y(b)||0===b.length||sa.test(b))&&f(Error(C(a,1,n)+'must be a non-empty string and can\'t contain ".", "#", "$", "[", or "]".'))}function E(a,b){".info"===F(b)&&f(Error(a+" failed: Can't modify data under /.info/"))};function G(a,b,c,d,e,g,h){this.n=a;this.path=b;this.fa=c;this.ja=Ba.test(d)?Number(d):d;this.va=e;this.na=Ba.test(g)?Number(g):g;this.ma=h;x(this.ja)&&(x(this.na)&&x(this.fa))&&f("fb.api.Query: Can't combine startAt(), endAt(), and limit().")}G.prototype.Db=function(a,b){A("fb.api.Query.on",2,2,arguments.length);xa("fb.api.Query.on",a,n);D("fb.api.Query.on",2,b,n);this.n.ab(this,a,b);return b};G.prototype.on=G.prototype.Db;
G.prototype.Cb=function(a,b){A("fb.api.Query.off",0,2,arguments.length);xa("fb.api.Query.off",a,k);D("fb.api.Query.off",2,b,k);this.n.Ta(this,a,b)};G.prototype.off=G.prototype.Cb;G.prototype.Dc=function(a,b){function c(g){e&&(e=n,d.Cb(a,c),b(g))}A("fb.api.Query.once",2,2,arguments.length);xa("fb.api.Query.once",a,n);D("fb.api.Query.once",2,b,n);var d=this,e=k;this.Db(a,c)};G.prototype.once=G.prototype.Dc;
G.prototype.yc=function(a){A("fb.api.Query.limit",1,1,arguments.length);(!da(a)||Math.floor(a)!==a||0>=a)&&f("fb.api.Query.limit: First argument must be a positive integer.");return new G(this.n,this.path,a,this.ja,this.va,this.na,this.ma)};G.prototype.limit=G.prototype.yc;G.prototype.Lc=function(a,b){A("fb.api.Query.startAt",0,2,arguments.length);wa("fb.api.Query.startAt",1,a,k);za("fb.api.Query.startAt",b);x(a)||(b=a=m);return new G(this.n,this.path,this.fa,a,b,this.na,this.ma)};
G.prototype.startAt=G.prototype.Lc;G.prototype.tc=function(a,b){A("fb.api.Query.endAt",0,2,arguments.length);wa("fb.api.Query.endAt",1,a,k);za("fb.api.Query.endAt",b);return new G(this.n,this.path,this.fa,this.ja,this.va,a,b)};G.prototype.endAt=G.prototype.tc;function Ca(a){var b={};x(a.ja)&&(b.sp=a.ja);x(a.va)&&(b.sn=a.va);x(a.na)&&(b.ep=a.na);x(a.ma)&&(b.en=a.ma);x(a.fa)&&(b.l=a.fa);return b}G.prototype.qa=function(){var a=Da(Ca(this));return"{}"===a?"default":a};function H(a){if(a instanceof H)return a;if(1==arguments.length){this.k=a.split("/");for(var b=0,c=0;c<this.k.length;c++)0<this.k[c].length&&(this.k[b]=this.k[c],b++);this.k.length=b;this.O=0}else this.k=arguments[0],this.O=arguments[1]}function F(a){return a.O>=a.k.length?m:a.k[a.O]}function J(a){var b=a.O;b<a.k.length&&b++;return new H(a.k,b)}H.prototype.toString=function(){for(var a="",b=this.O;b<this.k.length;b++)""!==this.k[b]&&(a+="/"+this.k[b]);return a||"/"};
H.prototype.parent=function(){if(this.O>=this.k.length)return m;for(var a=[],b=this.O;b<this.k.length-1;b++)a.push(this.k[b]);return new H(a,0)};H.prototype.G=function(a){for(var b=[],c=this.O;c<this.k.length;c++)b.push(this.k[c]);if(a instanceof H)for(c=a.O;c<a.k.length;c++)b.push(a.k[c]);else{a=a.split("/");for(c=0;c<a.length;c++)0<a[c].length&&b.push(a[c])}return new H(b,0)};H.prototype.e=function(){return this.O>=this.k.length};
function Ea(a,b){var c=F(a);if(c===m)return b;if(c===F(b))return Ea(J(a),J(b));f("INTERNAL ERROR: innerPath ("+b+") is not within outerPath ("+a+")")};function Fa(){this.children={};this.zb=0;this.value=m}function Ga(a,b,c){this.eb=a?a:"";this.Pa=b?b:m;this.m=c?c:new Fa}function K(a,b){for(var c=b instanceof H?b:new H(b),d=a,e;(e=F(c))!==m;)d=new Ga(e,d,e in d.m.children?d.m.children[e]:new Fa),c=J(c);return d}s=Ga.prototype;s.j=function(){return this.m.value};function L(a,b){M("undefined"!==typeof b);a.m.value=b;Ha(a)}s.cb=function(){return 0<this.m.zb};s.e=function(){return this.j()===m&&!this.cb()};
s.D=function(a){for(var b in this.m.children)a(new Ga(b,this,this.m.children[b]))};function Ia(a,b,c,d){c&&!d&&b(a);a.D(function(a){Ia(a,b,k,d)});c&&d&&b(a)}function Ja(a,b){for(var c=a.parent();c!==m;){if(b(c))return k;c=c.parent()}return n}s.path=function(){return new H(this.Pa===m?this.eb:this.Pa.path()+"/"+this.eb)};s.name=o("eb");s.parent=o("Pa");
function Ha(a){if(a.Pa!==m){var b=a.Pa,c=a.eb,d=a.e(),e=c in b.m.children;d&&e?(delete b.m.children[c],b.m.zb--,Ha(b)):!d&&!e&&(b.m.children[c]=a.m,b.m.zb++,Ha(b))}};function N(a,b){this.xa=a?a:Ka;this.S=b?b:La}function Ka(a,b){return a<b?-1:a>b?1:0}s=N.prototype;s.X=function(a,b){return new N(this.xa,this.S.X(a,b,this.xa).copy(m,m,n,m,m))};s.remove=function(a){return new N(this.xa,this.S.remove(a,this.xa).copy(m,m,n,m,m))};s.get=function(a){for(var b,c=this.S;!c.e();){b=this.xa(a,c.key);if(0===b)return c.value;0>b?c=c.left:0<b&&(c=c.right)}return m};
function Ma(a,b){for(var c,d=a.S,e=m;!d.e();){c=a.xa(b,d.key);if(0===c){if(d.left.e())return e?e.key:m;for(d=d.left;!d.right.e();)d=d.right;return d.key}0>c?d=d.left:0<c&&(e=d,d=d.right)}f("Attempted to find predecessor key for a nonexistent key.  What gives?")}s.e=function(){return this.S.e()};s.count=function(){return this.S.count()};s.Ka=function(){return this.S.Ka()};s.Ca=function(){return this.S.Ca()};s.da=function(a){return this.S.da(a)};s.sa=function(a){return this.S.sa(a)};
s.za=function(a){return new Na(this.S,a)};function Na(a,b){this.hc=b;for(this.fb=[];!a.e();)this.fb.push(a),a=a.left}function Oa(a){if(0===a.fb.length)return m;var b=a.fb.pop(),c;c=a.hc?a.hc(b.key,b.value):{key:b.key,value:b.value};for(b=b.right;!b.e();)a.fb.push(b),b=b.left;return c}function Pa(a,b,c,d,e){this.key=a;this.value=b;this.color=c!=m?c:k;this.left=d!=m?d:La;this.right=e!=m?e:La}s=Pa.prototype;
s.copy=function(a,b,c,d,e){return new Pa(a!=m?a:this.key,b!=m?b:this.value,c!=m?c:this.color,d!=m?d:this.left,e!=m?e:this.right)};s.count=function(){return this.left.count()+1+this.right.count()};s.e=p(n);s.da=function(a){return this.left.da(a)||a(this.key,this.value)||this.right.da(a)};s.sa=function(a){return this.right.sa(a)||a(this.key,this.value)||this.left.sa(a)};function Qa(a){return a.left.e()?a:Qa(a.left)}s.Ka=function(){return Qa(this).key};
s.Ca=function(){return this.right.e()?this.key:this.right.Ca()};s.X=function(a,b,c){var d,e;e=this;d=c(a,e.key);e=0>d?e.copy(m,m,m,e.left.X(a,b,c),m):0===d?e.copy(m,b,m,m,m):e.copy(m,m,m,m,e.right.X(a,b,c));return Ra(e)};function Sa(a){if(a.left.e())return La;!a.left.B()&&!a.left.left.B()&&(a=Ta(a));a=a.copy(m,m,m,Sa(a.left),m);return Ra(a)}
s.remove=function(a,b){var c,d;c=this;if(0>b(a,c.key))!c.left.e()&&(!c.left.B()&&!c.left.left.B())&&(c=Ta(c)),c=c.copy(m,m,m,c.left.remove(a,b),m);else{c.left.B()&&(c=Ua(c));!c.right.e()&&(!c.right.B()&&!c.right.left.B())&&(c=Va(c),c.left.left.B()&&(c=Ua(c),c=Va(c)));if(0===b(a,c.key)){if(c.right.e())return La;d=Qa(c.right);c=c.copy(d.key,d.value,m,m,Sa(c.right))}c=c.copy(m,m,m,m,c.right.remove(a,b))}return Ra(c)};s.B=o("color");
function Ra(a){a.right.B()&&!a.left.B()&&(a=Wa(a));a.left.B()&&a.left.left.B()&&(a=Ua(a));a.left.B()&&a.right.B()&&(a=Va(a));return a}function Ta(a){a=Va(a);a.right.left.B()&&(a=a.copy(m,m,m,m,Ua(a.right)),a=Wa(a),a=Va(a));return a}function Wa(a){var b;b=a.copy(m,m,k,m,a.right.left);return a.right.copy(m,m,a.color,b,m)}function Ua(a){var b;b=a.copy(m,m,k,a.left.right,m);return a.left.copy(m,m,a.color,m,b)}
function Va(a){var b,c;b=a.left.copy(m,m,!a.left.color,m,m);c=a.right.copy(m,m,!a.right.color,m,m);return a.copy(m,m,!a.color,b,c)}function Xa(){}s=Xa.prototype;s.copy=function(){return this};s.X=function(a,b){return new Pa(a,b,i,i,i)};s.remove=function(){return this};s.get=p(m);s.count=p(0);s.e=p(k);s.da=p(n);s.sa=p(n);s.Ka=p(m);s.Ca=p(m);s.B=p(n);var La=new Xa;function Ya(){};function Za(){this.u=[];this.yb=[];this.rc=[];this.lb=[];this.lb[0]=128;for(var a=1;64>a;++a)this.lb[a]=0;this.reset()}ha(Za,Ya);Za.prototype.reset=function(){this.u[0]=1732584193;this.u[1]=4023233417;this.u[2]=2562383102;this.u[3]=271733878;this.u[4]=3285377520;this.Kb=this.Ha=0};
function $a(a,b){var c;c||(c=0);for(var d=a.rc,e=c;e<c+64;e+=4)d[e/4]=b[e]<<24|b[e+1]<<16|b[e+2]<<8|b[e+3];for(e=16;80>e;e++){var g=d[e-3]^d[e-8]^d[e-14]^d[e-16];d[e]=(g<<1|g>>>31)&4294967295}c=a.u[0];for(var h=a.u[1],j=a.u[2],l=a.u[3],w=a.u[4],u,e=0;80>e;e++)40>e?20>e?(g=l^h&(j^l),u=1518500249):(g=h^j^l,u=1859775393):60>e?(g=h&j|l&(h|j),u=2400959708):(g=h^j^l,u=3395469782),g=(c<<5|c>>>27)+g+w+u+d[e]&4294967295,w=l,l=j,j=(h<<30|h>>>2)&4294967295,h=c,c=g;a.u[0]=a.u[0]+c&4294967295;a.u[1]=a.u[1]+h&
4294967295;a.u[2]=a.u[2]+j&4294967295;a.u[3]=a.u[3]+l&4294967295;a.u[4]=a.u[4]+w&4294967295}Za.prototype.update=function(a,b){x(b)||(b=a.length);var c=this.yb,d=this.Ha,e=0;if(y(a))for(;e<b;)c[d++]=a.charCodeAt(e++),64==d&&($a(this,c),d=0);else for(;e<b;)c[d++]=a[e++],64==d&&($a(this,c),d=0);this.Ha=d;this.Kb+=b};function ab(){this.wa={};this.length=0}ab.prototype.setItem=function(a,b){this.wa.hasOwnProperty(a)||(this.length+=1);this.wa[a]=b};ab.prototype.getItem=function(a){return this.wa.hasOwnProperty(a)?this.wa[a]:m};ab.prototype.removeItem=function(a){this.wa.hasOwnProperty(a)&&(this.length-=1,delete this.wa[a])};var bb=m;
if("undefined"!==typeof sessionStorage)try{sessionStorage.setItem("firebase-sentinel","cache"),sessionStorage.removeItem("firebase-sentinel"),bb=sessionStorage}catch(cb){bb=new ab}else bb=new ab;function db(a,b,c,d){this.host=a;this.Hb=b;this.La=c;this.ea=d||bb.getItem(c)||this.host}function eb(a,b){b!==a.ea&&(a.ea=b,"s-"===a.ea.substr(0,2)&&bb.setItem(a.La,a.ea))};var fb,gb,hb,ib;function jb(){return t.navigator?t.navigator.userAgent:m}ib=hb=gb=fb=n;var kb;if(kb=jb()){var lb=t.navigator;fb=0==kb.indexOf("Opera");gb=!fb&&-1!=kb.indexOf("MSIE");hb=!fb&&-1!=kb.indexOf("WebKit");ib=!fb&&!hb&&"Gecko"==lb.product}var mb=gb,nb=ib,qb=hb;var rb;if(fb&&t.opera){var sb=t.opera.version;"function"==typeof sb&&sb()}else nb?rb=/rv\:([^\);]+)(\)|;)/:mb?rb=/MSIE\s+([^\);]+)(\)|;)/:qb&&(rb=/WebKit\/(\S+)/),rb&&rb.exec(jb());var tb=m;var ub,vb=1;ub=function(){return vb++};function M(a,b){a||f(Error("Firebase INTERNAL ASSERT FAILED:"+b))}
function wb(a){for(var b=[],c=0,d=0;d<a.length;d++){var e=a.charCodeAt(d);128>e?b[c++]=e:(2048>e?b[c++]=e>>6|192:(b[c++]=e>>12|224,b[c++]=e>>6&63|128),b[c++]=e&63|128)}a=new Za;a.update(b);b=[];d=8*a.Kb;56>a.Ha?a.update(a.lb,56-a.Ha):a.update(a.lb,64-(a.Ha-56));for(c=63;56<=c;c--)a.yb[c]=d&255,d/=256;$a(a,a.yb);for(c=d=0;5>c;c++)for(e=24;0<=e;e-=8)b[d++]=a.u[c]>>e&255;ca(b)||f(Error("encodeByteArray takes an array as a parameter"));if(!tb){tb={};for(a=0;65>a;a++)tb[a]="ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/=".charAt(a)}a=
tb;c=[];for(d=0;d<b.length;d+=3){var g=b[d],h=(e=d+1<b.length)?b[d+1]:0,j=d+2<b.length,l=j?b[d+2]:0,w=g>>2,g=(g&3)<<4|h>>4,h=(h&15)<<2|l>>6,l=l&63;j||(l=64,e||(h=64));c.push(a[w],a[g],a[h],a[l])}return c.join("")}function xb(){for(var a="",b=0;b<arguments.length;b++)a=ca(arguments[b])?a+xb.apply(m,arguments[b]):"object"===typeof arguments[b]?a+oa(arguments[b]):a+arguments[b],a+=" ";return a}var yb=m;function zb(){if(yb){var a=xb.apply(m,arguments);yb(a)}}
function Ab(a){return function(){zb(a,arguments)}}function Bb(){if("undefined"!==typeof console){var a=xb.apply(m,arguments);console.log("FIREBASE INTERNAL ERROR: "+a)}}function Cb(){if("undefined"!==typeof console){var a=xb.apply(m,arguments);console.log("FIREBASE WARNING: "+a)}}function Db(a){for(var b="",a=a.split("/"),c=0;c<a.length;c++)if(0<a[c].length){var d=a[c];try{d=decodeURIComponent(d.replace(/\+/g," "))}catch(e){}b+="/"+d}return b}var Ba=/^[\-+]?[0-9]*\.?[0-9]+(e\-|e\+|E\-|E\+|e|E)?[0-9]*$/;
function Eb(a,b){return a!==b?a===m?-1:b===m?1:typeof a!==typeof b?"number"===typeof a?-1:1:a>b?1:-1:0}function Fb(a,b){if(b&&a in b)return b[a];f(Error("Missing required key ("+a+") in object: "+JSON.stringify(b)))}var Gb=0;function Da(a){if("object"!==typeof a||a===m)return oa(a);var b=[],c;for(c in a)b.push(c);b.sort();c="{";for(var d=0;d<b.length;d++)0!==d&&(c+=","),c+=oa(b[d]),c+=":",c+=Da(a[b[d]]);return c+"}"};function Hb(a,b){this.ka=a;M(this.ka!==m,"LeafNode shouldn't be created with null value.");this.Da="undefined"!==typeof b?b:m}s=Hb.prototype;s.Y=p(k);s.i=o("Da");s.xb=function(a){return new Hb(this.ka,a)};s.K=function(){return O};s.J=function(a){return F(a)===m?this:O};s.Q=p(m);s.A=function(a,b){return(new P(new N,this.Da)).A(a,b)};s.$a=function(a,b){var c=F(a);return c===m?b:this.A(c,O.$a(J(a),b))};s.e=p(n);s.gb=p(0);
s.T=function(a){return a&&this.i()!==m?{".value":this.j(),".priority":""+this.i()}:this.j()};s.hash=function(){var a="";this.i()!==m&&(a+="priority:"+this.i()+":");a+=typeof this.ka+":"+this.ka;return wb(a)};s.j=o("ka");s.toString=function(){return"string"===typeof this.ka?'"'+this.ka+'"':this.ka};function P(a,b){this.M=a||new N;this.Da="undefined"!==typeof b?b:m}s=P.prototype;s.Y=p(n);s.i=o("Da");s.xb=function(a){return new P(this.M,a)};s.A=function(a,b){var c=this.M.remove(a);b&&b.e()&&(b=m);b!==m&&(c=c.X(a,b));return b&&b.i()!==m?new Ib(c,m,this.Da):new P(c,this.Da)};s.$a=function(a,b){var c=F(a);if(c===m)return b;var d=this.K(c).$a(J(a),b);return this.A(c,d)};s.e=function(){return this.M.e()};s.gb=function(){return this.M.count()};var Jb=/^\d+$/;s=P.prototype;
s.T=function(a){if(this.e())return m;var b={},c=0,d=0,e=k;this.D(function(g,h){b[g]=h.T(a);c++;e&&Jb.test(g)?d=Math.max(d,Number(g)):e=n});if(!a&&e&&d<2*c){var g=[],h;for(h in b)g[h]=b[h];return g}a&&this.i()!==m&&(b[".priority"]=""+this.i());return b};s.hash=function(){var a="";this.i()!==m&&(a+="priority:"+this.i()+":");this.D(function(b,c){var d=c.hash();""!==d&&(a+=":"+b+":"+d)});return""===a?"":wb(a)};s.K=function(a){a=this.M.get(a);return a===m?O:a};
s.J=function(a){var b=F(a);return b===m?this:this.K(b).J(J(a))};s.Q=function(a){return Ma(this.M,a)};s.Vb=function(){return this.M.Ka()};s.Xb=function(){return this.M.Ca()};s.D=function(a){return this.M.da(a)};s.Ab=function(a){return this.M.sa(a)};s.za=function(){return this.M.za()};s.toString=function(){var a="{",b=k;this.D(function(c,d){b?b=n:a+=", ";a+='"'+c+'" : '+d.toString()});return a+="}"};var O=new P(new N);function Ib(a,b,c){P.call(this,a,c);b===m&&(b=new N(Kb),a.da(function(a,c){b=b.X({name:a,ga:c.i()},c)}));this.ua=b}ha(Ib,P);s=Ib.prototype;s.A=function(a,b){var c=this.K(a),d=this.M,e=this.ua;c!==m&&(d=d.remove(a),e=e.remove({name:a,ga:c.i()}));b&&b.e()&&(b=m);b!==m&&(d=d.X(a,b),e=e.X({name:a,ga:b.i()},b));return new Ib(d,e,this.i())};s.Q=function(a,b){var c=Ma(this.ua,{name:a,ga:b.i()});return c?c.name:m};s.D=function(a){return this.ua.da(function(b,c){return a(b.name,c)})};
s.Ab=function(a){return this.ua.sa(function(b,c){return a(b.name,c)})};s.za=function(){return this.ua.za(function(a,b){return{key:a.name,value:b}})};s.Vb=function(){return this.ua.Ka().name};s.Xb=function(){return this.ua.Ca().name};function Q(a,b){if("object"!==typeof a)return new Hb(a,b);if(a===m)return O;var c=m;".priority"in a?c=a[".priority"]:"undefined"!==typeof b&&(c=b);c!==m&&(c=Ba.test(c)?Number(c):c);if(".value"in a&&a[".value"]!==m)return new Hb(a[".value"],c);var c=new P(new N,c),d;for(d in a)if(a.hasOwnProperty(d)&&"."!==d.substring(0,1)){var e=Q(a[d]);if(e.Y()||!e.e())c=c.A(d,e)}return c}function Kb(a,b){return Eb(a.ga,b.ga)||(a.name!==b.name?a.name<b.name?-1:1:0)};function R(a,b){this.m=a;this.qb=b}R.prototype.T=function(){A("Firebase.DataSnapshot.val",0,0,arguments.length);return this.m.T()};R.prototype.val=R.prototype.T;R.prototype.uc=function(){A("Firebase.DataSnapshot.exportVal",0,0,arguments.length);return this.m.T(k)};R.prototype.exportVal=R.prototype.uc;R.prototype.G=function(a){A("Firebase.DataSnapshot.child",0,1,arguments.length);da(a)&&(a=String(a));Aa("Firebase.DataSnapshot.child",a);var b=new H(a),c=this.qb.G(b);return new R(this.m.J(b),c)};
R.prototype.child=R.prototype.G;R.prototype.wc=function(a){A("Firebase.DataSnapshot.hasChild",1,1,arguments.length);Aa("Firebase.DataSnapshot.hasChild",a);var b=new H(a);return!this.m.J(b).e()};R.prototype.hasChild=R.prototype.wc;R.prototype.i=function(){A("Firebase.DataSnapshot.getPriority",0,0,arguments.length);var a=this.m.i();return a===m?a:""+a};R.prototype.getPriority=R.prototype.i;
R.prototype.forEach=function(a){A("Firebase.DataSnapshot.forEach",1,1,arguments.length);D("Firebase.DataSnapshot.forEach",1,a,n);if(this.m.Y())return n;var b=this;return this.m.D(function(c,d){return a(new R(d,b.qb.G(c)))})};R.prototype.forEach=R.prototype.forEach;R.prototype.cb=function(){A("Firebase.DataSnapshot.hasChildren",0,0,arguments.length);return this.m.Y()?n:!this.m.e()};R.prototype.hasChildren=R.prototype.cb;
R.prototype.name=function(){A("Firebase.DataSnapshot.name",0,0,arguments.length);return this.qb.name()};R.prototype.name=R.prototype.name;R.prototype.gb=function(){A("Firebase.DataSnapshot.numChildren",0,0,arguments.length);return this.m.gb()};R.prototype.numChildren=R.prototype.gb;R.prototype.Fc=function(){A("Firebase.DataSnapshot.ref",0,0,arguments.length);return this.qb};R.prototype.ref=R.prototype.Fc;var Lb={};var Mb=m;"undefined"!==typeof MozWebSocket?Mb=MozWebSocket:"undefined"!==typeof WebSocket&&(Mb=WebSocket);function Nb(a,b,c){this.Nb=a;this.c=Ab(this.Nb);this.Ia=m;this.state=0;this.frames=m;this.nc=0;this.ya=(b.Hb?"wss://":"ws://")+b.ea+"/.ws?v=4";b.host!==b.ea&&(this.ya=this.ya+"&ns="+b.La);c&&(this.ya=this.ya+"&s="+c)}var Ob;
Nb.prototype.open=function(a,b){this.Ma=b;this.jb=a;this.c("websocket connecting to "+this.ya);this.N=new Mb(this.ya);this.Sb=n;var c=this;this.N.onopen=function(){c.c("Websocket connected.");c.state=1;c.Sb=k};this.N.onclose=function(){c.c("Websocket connection was disconnected.");c.N=m;Pb(c)};this.N.onmessage=function(a){c.N!==m&&(a=a.data,1===c.state?(c.nc=Number(a),c.state=2,c.frames=[]):2===c.state?(c.frames.push(a),c.frames.length==c.nc&&(a="undefined"!==typeof JSON&&x(JSON.parse)?JSON.parse(c.frames.join("")):
ia(c.frames.join("")),c.state=1,Qb(c),c.jb(a))):Bb("Websocket got a frame in an unknown state: "+c.state))};this.N.onerror=function(){c.c("WebSocket error.  Closing connection.");Pb(c)}};Nb.prototype.start=function(){};Nb.isAvailable=function(){return!("undefined"!==typeof navigator&&"Opera"===navigator.appName)&&Mb!==m&&!Ob};
Nb.prototype.send=function(a){Qb(this);a=oa(a);if(16384>=a.length)a=[a];else{for(var b=[],c=0;c<a.length;c+=16384)c+16384>a?b.push(a.substring(c,a.length)):b.push(a.substring(c,c+16384));a=b}this.N.send(String(a.length));for(b=0;b<a.length;b++)this.N.send(a[b])};function Rb(a){a.$b=k;a.Ia&&(clearTimeout(a.Ia),a.Ia=m);a.N&&(a.N.close(),a.N=m)}function Pb(a){a.$b||(a.c("WebSocket is closing itself"),Rb(a),a.Ma&&(a.Ma(a.Sb),a.Ma=m))}
Nb.prototype.close=function(){this.$b||(this.c("WebSocket is being closed"),Rb(this))};function Qb(a){clearTimeout(a.Ia);a.Ia=setInterval(function(){a.N.send("0");Qb(a)},45E3)};function Sb(){var a=[],b=Tb,c;for(c in b)if(b.hasOwnProperty(c)){var d=b[c];d&&d.isAvailable()&&a.push(d)}this.vb=a}var Tb=[Nb];function S(a,b,c,d,e,g){this.id=a;this.c=Ab("c:"+this.id+":");this.Cc=c;this.Na=d;this.pa=e;this.Fb=g;this.F=b;this.mb=[];this.Ob=0;this.Lb=new Sb;this.$=0;this.c("Connection created");Ub(this)}function Ub(a){var b;var c=a.Lb;0<c.vb.length?b=c.vb[0]:f(Error("No transports available"));a.C=new b("c:"+a.id+":"+a.Ob++,a.F);b=Vb(a,a.C);c=Wb(a,a.C);a.Ya=a.C;a.Va=a.C;a.C.open(b,c);a.o=m}
function Wb(a,b){return function(c){b===a.C?(a.C=m,!c&&0===a.$?(a.c("Realtime connection failed."),"s-"===a.F.ea.substr(0,2)&&(bb.removeItem(a.F.La),a.F.ea=a.F.host)):1===a.$&&a.c("Realtime connection lost."),a.close()):b===a.o?(c=a.o,a.o=m,(a.Ya===c||a.Va===c)&&a.close()):a.c("closing an old connection")}}
function Vb(a,b){return function(c){if(2!=a.$)if(b===a.Va){var d=Fb("t",c),c=Fb("d",c);if("c"==d){if(d=Fb("t",c),"d"in c)if(c=c.d,"h"===d){var d=c.ts,e=c.v,g=c.h;a.Kc=c.s;eb(a.F,g);if(0==a.$&&(a.C.start(),c=a.C,a.c("Realtime connection established."),a.C=c,a.$=1,a.Na&&(a.Na(d),a.Na=m),"4"!==e&&Cb("Protocol version mismatch detected"),c=1<a.Lb.vb.length?a.Lb.vb[1]:m))a.o=new c("c:"+a.id+":"+a.Ob++,a.F,a.Kc),a.o.open(Vb(a,a.o),Wb(a,a.o))}else if("n"===d){a.c("recvd end transmission on primary");a.Va=
a.o;for(c=0;c<a.mb.length;++c)a.hb(a.mb[c]);a.mb=[];Xb(a)}else"s"===d?(a.c("Connection shutdown command received. Shutting down..."),a.Fb&&(a.Fb(c),a.Fb=m),a.pa=m,a.close()):"r"===d?(a.c("Reset packet received.  New host: "+c),eb(a.F,c),1===a.$?a.close():(Yb(a),Ub(a))):Bb("Unknown control packet command: "+d)}else"d"==d&&a.hb(c)}else b===a.o?(d=Fb("t",c),c=Fb("d",c),"c"==d?"t"in c&&(c=c.t,"a"===c?(a.o.start(),a.c("sending client ack on secondary"),a.o.send({t:"c",d:{t:"a",d:{}}}),a.c("Ending transmission on primary"),
a.C.send({t:"c",d:{t:"n",d:{}}}),a.Ya=a.o,Xb(a)):"r"===c&&(a.c("Got a reset on secondary, closing it"),a.o.close(),(a.Ya===a.o||a.Va===a.o)&&a.close())):"d"==d?a.mb.push(c):f(Error("Unknown protocol layer: "+d))):a.c("message on old connection")}}S.prototype.Ib=function(a){a={t:"d",d:a};1!==this.$&&f("Connection is not connected");this.Ya.send(a)};function Xb(a){a.Ya===a.o&&a.Va===a.o&&(a.c("cleaning up and promoting a connection: "+a.o.Nb),a.C=a.o,a.o=m)}S.prototype.hb=function(a){this.Cc(a)};
S.prototype.close=function(){2!==this.$&&(this.c("Closing realtime connection."),this.$=2,Yb(this),this.pa&&(this.pa(),this.pa=m))};function Yb(a){a.c("Shutting down all connections");a.C&&(a.C.close(),a.C=m);a.o&&(a.o.close(),a.o=m)};function T(a,b,c,d){this.id=Zb++;this.c=Ab("p:"+this.id+":");this.Xa=k;this.U={};this.L=[];this.Oa=0;this.Eb={};this.W=n;this.pb=1E3;this.cc=c;this.pa=d;this.F=a;this.ib=b;this.nb=[];this.ia={};this.Jc=0;this.Ja=this.ac=m;setTimeout(z(this.Qb,this),0)}var Zb=0,$b=0;s=T.prototype;
s.ta=function(a,b,c,d){var e=++this.Jc,a={r:e,a:a,b:b};this.c(JSON.stringify(a));this.W?this.Sa.Ib(a):this.nb.push(a);var g=this,a=setTimeout(function(){var a=g.ia[e];a&&(delete g.ia[e],a.V&&a.V.kb&&a.V.kb())},45E3);this.ia[e]={V:{jb:c,kb:d},lc:a}};function ac(a,b,c,d){var e=Da(c);a.c("Listen on "+b+" for "+e);b={p:b};"default"!==e&&(b.q=c);a.ta("l",b,function(b){a.c("listen response",b);d&&d(b.s)},function(){a.c("timed out on listen...")})}
s.Ga=function(a,b){this.bb={sc:a,Tb:n,ba:b};this.c("Authenticating using credential: "+this.bb);bc(this)};s.Za=function(){delete this.bb;this.W&&this.ta("unauth",{},function(){},function(){})};function bc(a){var b=a.bb;a.W&&b&&a.ta("auth",{cred:b.sc},function(c){(c="ok"==c.s)||delete a.bb;b.Tb||(b.Tb=k,b.ba&&b.ba(c))},function(){a.c("timed out on auth...")})}
s.Mc=function(a,b){var c=Da(b);M(this.U[a][c],"unlisten() called for path/queryId we're not listening on.");delete this.U[a][c];if(this.W){c=Da(b);this.c("Unlisten on "+a+" for "+c);var d=this,e={p:a};"default"!==c&&(e.q=b);this.ta("u",e,m,function(){d.c("timed out on unlisten...")})}};s.Ma=function(a,b){this.Eb[a]=b;this.W&&cc(this,a,b)};
function cc(a,b,c){b={p:b,d:c};a.c("onDisconnect",b);a.ta("o",b,function(a){"ok"!==a.s&&f("onDisconnect failed: "+oa(a.d))},function(){a.c("timed out on onDisconnect...")})}s.put=function(a,b,c,d){dc(this,"p",a,b,c,d)};function dc(a,b,c,d,e,g){c={p:c,d:d};x(g)&&(c.h=g);a.L.push({action:b,gc:c,H:e});a.Oa++;b=a.L.length-1;a.W&&ec(a,b)}
function ec(a,b){var c=a.L[b].action,d=a.L[b].H;a.ta(c,a.L[b].gc,function(e){a.c(c+" response",e);delete a.L[b];a.Oa--;0===a.Oa&&(a.L=[]);d&&d(e.s)},function(){a.c("timed out on put...")})}
s.hb=function(a){if("r"in a){this.c("from server: "+JSON.stringify(a));var b=a.r,c=this.ia[b];c&&(delete this.ia[b],clearTimeout(c.lc),c.V&&c.V.jb&&c.V.jb(a.b))}else"error"in a&&f("A server-side error has occurred: "+a.error),"a"in a&&(b=a.a,a=a.b,this.c("handleServerMessage",b,a),"d"===b?this.ib(a.p,a.d):"m"===b?this.ib(a.p,a.d,k):Bb("Unrecognized action received from server: "+oa(b)+"\nAre you using the latest client?"))};
s.Na=function(a){this.c("connection ready");this.W=k;this.Ja=(new Date).getTime();Gb=a-(new Date).getTime();for(a=0;a<this.nb.length;a++)this.Sa.Ib(this.nb[a]);this.nb=[];bc(this);for(var b in this.U)for(var c in this.U[b])a=this.U[b][c],ac(this,b,a.Ec,a.H);for(b in this.Eb)cc(this,b,this.Eb[b]);for(b=0;b<this.L.length;b++)this.L[b]&&ec(this,b);this.cc&&this.cc()};
s.ec=function(){this.W=n;this.c("data client disconnected");if(!this.Xa){for(var a=0;a<this.L.length;a++){var b=this.L[a];b&&"h"in b.gc&&(b.H&&b.H("disconnect"),delete this.L[a],this.Oa--)}0===this.Oa&&(this.L=[]);for(var c in this.ia)a=this.ia[c],delete this.ia[c],a!==m&&(a.V&&a.V.kb&&a.V.kb(),clearTimeout(a.lc))}var d=z(function(){this.Qb()},this);this.Xa?(this.Ja&&(3E4<(new Date).getTime()-this.Ja&&(this.pb=1E3),this.Ja=m),c=Math.max(0,this.pb-((new Date).getTime()-this.ac)),c*=Math.random(),this.c("Trying to reconnect in "+
c+"ms"),setTimeout(d,c),this.pb=Math.min(3E4,1.3*this.pb)):this.ic=function(){console.log("called");setTimeout(d,0)};this.pa&&this.pa()};s.Qb=function(){if(this.Xa){this.c("Making a connection attempt");this.ac=(new Date).getTime();this.Ja=m;var a=z(this.hb,this),b=z(this.Na,this),c=z(this.ec,this),d=this.id+":"+$b++;this.Sa=new S(d,this.F,a,b,c,function(a){f(Error(a))})}};s.Aa=function(){this.Xa=n;this.Sa?this.Sa.close():this.ec()};s.Ua=function(){this.Xa=k;this.ic();this.ic=i};function fc(){this.Ea=O}function U(a,b){return a.Ea.J(b)}function V(a,b,c){a.Ea=a.Ea.$a(b,c)};function gc(){this.Wa=new fc;this.R=new fc;this.la=new fc;this.Qa=new Ga}function hc(a,b){for(var c=U(a.Wa,b),d=U(a.R,b),e=K(a.Qa,b),g=n,h=e;h!==m;){if(h.j()!==m){g=k;break}h=h.parent()}if(g)return n;c=ic(c,d,e);return c!==d?(V(a.R,b,c),k):n}function ic(a,b,c){if(c.e())return a;if(c.j()!==m)return b;a=a||O;c.D(function(d){var d=d.name(),e=a.K(d),g=b.K(d),h=K(c,d),e=ic(e,g,h);a=a.A(d,e)});return a}gc.prototype.set=function(a,b){var c=ub();L(K(this.Qa,a),c);V(this.R,a,b);return c};
function jc(a,b,c){a=K(a.Qa,b);b=a.j();M(b!==m,"pendingPut should not be null.");b===c&&L(a,m)};function kc(){this.oa=[]}function lc(a,b){if(0!==b.length){a.oa.push.apply(a.oa,b);for(var c=0;c<a.oa.length;c++)if(a.oa[c]){var d=a.oa[c];a.oa[c]=m;var e=d.ba;e(d.kc,d.Ra)}a.oa=[]}};function W(a,b,c,d){this.type=a;this.Z=b;this.P=c;this.Ra=d};function oc(a){this.z=a;this.ca=[];this.Rb=new kc}function pc(a,b,c){for(var d=n,e=a.ca.length-1;0<=e;e--){var g=a.ca[e];if(!b||g.type===b&&(!c||g.ba===c))if(a.ca.splice(e,1),d=k,b&&c)break}return d}oc.prototype.ob=function(a,b){b=this.Gb(a,b);qc(this,b)};
function qc(a,b){for(var c=[],d=0;d<b.length;d++){var e=b[d],g=e.type,h=new X(a.z.n,a.z.path);b[d].P&&(h=h.G(b[d].P));h=new R(b[d].Z,h);"value"===e.type&&!h.cb()?g+="("+h.T()+")":"value"!==e.type&&(g+=" "+h.name());zb(a.z.n.w.id+": event:"+a.z.path+":"+a.z.qa()+":"+g);for(g=0;g<a.ca.length;g++){var j=a.ca[g];b[d].type===j.type&&c.push({ba:j.ba,kc:h,Ra:e.Ra})}}lc(a.Rb,c)}function rc(a){var b=[];if(!a.Y()){var c=m;a.D(function(a,e){b.push(new W("child_added",e,a,c));c=a})}return b}
function sc(a){a.Ba||(a.Ba=k,qc(a,[new W("value",a.f)]))};function tc(a,b){oc.call(this,a);this.f=b}ha(tc,oc);tc.prototype.Gb=function(a,b){this.f=a;this.Ba&&b.push(new W("value",this.f));return b};function uc(a,b){this.Pb=a;this.dc=b}function vc(a,b,c,d){var e,g=[];c===d?e=n:c.Y()&&d.Y()?e=c.j()!==d.j():c.Y()?(wc(a,b,O,d,g),e=k):d.Y()?(wc(a,b,c,O,g),e=k):e=wc(a,b,c,d,g);(e=e||c.i()!==d.i())&&a.dc(b,d,g);return e}
function wc(a,b,c,d,e){var g=n,h=!K(a.Pb,b).e(),j=[],l=[],w=[],u={},I={},q,v,r,B;q=c.za();r=Oa(q);v=d.za();for(B=Oa(v);r!==m||B!==m;){c=r===m?1:B===m?-1:r.key===B.key?0:Kb({name:r.key,ga:r.value.i()},{name:B.key,ga:B.value.i()});if(0>c)g=u[r.key],x(g)?(w.push({Ub:r,mc:j[g]}),j[g]=m):(I[r.key]=l.length,l.push(r)),g=k,r=Oa(q);else{if(0<c)g=I[B.key],x(g)?(w.push({Ub:l[g],mc:B}),l[g]=m):(u[B.key]=j.length,j.push(B)),g=k;else{c=b.G(B.key);if(c=vc(a,c,r.value,B.value))r=d.Q(B.key,B.value),e.push(new W("child_changed",
B.value,B.key,r)),g=k;r=Oa(q)}B=Oa(v)}if(!h&&g)return k}for(h=0;h<l.length;h++)if(u=l[h])c=b.G(u.key),vc(a,c,u.value,O),e.push(new W("child_removed",u.value,u.key));for(h=0;h<j.length;h++)if(l=j[h])c=b.G(l.key),r=d.Q(l.key,l.value),vc(a,c,O,l.value),e.push(new W("child_added",l.value,l.key,r));for(h=0;h<w.length;h++)l=w[h].Ub,j=w[h].mc,c=b.G(j.key),r=d.Q(j.key,j.value),e.push(new W("child_moved",j.value,j.key,r)),(c=vc(a,c,l.value,j.value))&&e.push(new W("child_changed",j.value,j.key,r));return g}
;function xc(a,b){oc.call(this,a);this.f=O;this.Gb(b,rc(b))}ha(xc,oc);
xc.prototype.Gb=function(a,b){var c=[],d=this.z;x(this.z.va)&&c.push(function(a){return 0<=(a!==d.va?a<d.va?-1:1:0)});x(this.z.ma)&&c.push(function(a){return 0>=(a!==d.ma?a<d.ma?-1:1:0)});x(this.z.ja)&&c.push(function(a,b){return 0<=Eb(b,d.ja)});x(this.z.na)&&c.push(function(a,b){return 0>=Eb(b,d.na)});var e=m,g=m;if(x(this.z.fa))if(x(this.z.ja)){if(e=yc(a,c,this.z.fa,n)){var h=a.K(e).i();c.push(function(a,b){var c=Eb(b,h);return 0>c||0===c&&a<=e})}}else if(g=yc(a,c,this.z.fa,k)){var j=a.K(g).i();
c.push(function(a,b){var c=Eb(b,j);return 0<c||0===c&&a>=g})}for(var l=[],w=[],u=[],I=[],q=0;q<b.length;q++){var v=b[q].P,r=b[q].Z;switch(b[q].type){case "child_added":zc(c,v,r)&&(this.f=this.f.A(v,r),w.push(b[q]));break;case "child_removed":this.f.K(v).e()||(this.f=this.f.A(v,m),l.push(b[q]));break;case "child_changed":!this.f.K(v).e()&&zc(c,v,r)&&(this.f=this.f.A(v,r),I.push(b[q]));break;case "child_moved":var B=!this.f.K(v).e(),mc=zc(c,v,r);B?mc?(this.f=this.f.A(v,r),u.push(b[q])):(l.push(new W("child_removed",
this.f.K(v),v)),this.f=this.f.A(v,m)):mc&&(this.f=this.f.A(v,r),w.push(b[q]))}}var nc=e||g;if(nc){var Uc=(q=g!==m)?this.f.Vb():this.f.Xb(),ob=n,pb=n,ya=this;(q?a.Ab:a.D).call(a,function(a,b){ob?(l.push(new W("child_removed",ya.f.K(a),a)),ya.f=ya.f.A(a,m)):pb&&(w.push(new W("child_added",b,a)),ya.f=ya.f.A(a,b));a===Uc&&(pb=k);a===nc&&(ob=k);if(pb&&ob)return k})}for(q=0;q<w.length;q++)c=w[q],v=this.f.Q(c.P,c.Z),l.push(new W("child_added",c.Z,c.P,v));for(q=0;q<u.length;q++)c=u[q],v=this.f.Q(c.P,c.Z),
l.push(new W("child_moved",c.Z,c.P,v));for(q=0;q<I.length;q++)c=I[q],v=this.f.Q(c.P,c.Z),l.push(new W("child_changed",c.Z,c.P,v));this.Ba&&0<l.length&&l.push(new W("value",this.f));return l};function yc(a,b,c,d){var e=m;(d?a.Ab:a.D).call(a,function(a,d){if(zc(b,a,d)&&(e=a,c--,0===c))return k});return e}function zc(a,b,c){for(var d=0;d<a.length;d++)if(!a[d](b,c.i()))return n;return k};function Ac(a,b){this.w=a;this.g=b;this.bc=b.Ea;this.Fa=new Ga}
Ac.prototype.ab=function(a,b,c){var d=a.path,e=K(this.Fa,d),g=e.j();g===m&&(g={},L(e,g));var h=a.qa();if(!(h in g)){g=g||{};g[h]={};var j=g,l=n;Ja(e,function(a){a.j()&&(a.j()["default"]&&a.j()["default"].I)&&(l=k)});l||(j[h].I=Bc(this,a),"default"===h&&Ia(e,function(a){a=a.j();if(a!==m)for(var b in a)if(a[b].I){a[b].I();delete a[b].I}}))}e=g[h].view;e||(e=this.g.Ea.J(d),e="default"===a.qa()?new tc(a,e):new xc(a,e),g[h].view=e,(a=(a=Ja(K(this.Fa,d),function(a){if(a.j()&&a.j()["default"]&&a.j()["default"].view.Ba)return k}))||
this.w===m)&&sc(e));a=e;a.ca.push({type:b,ba:c});d=[];g=rc(a.f);a.Ba&&g.push(new W("value",a.f));for(h=0;h<g.length;h++)g[h].type===b&&(e=new X(a.z.n,a.z.path),g[h].P&&(e=e.G(g[h].P)),d.push({ba:c,kc:new R(g[h].Z,e),Ra:g[h].Ra}));lc(a.Rb,d)};
Ac.prototype.Ta=function(a,b,c){var d=K(this.Fa,a.path),e=d.j();if(!(e===m||!g in e)){var g=a.qa();if("default"!==g)d=e[g].view,pc(d,b,c),0<d.ca.length||(e[g].I&&(e[g].I(),delete e[g].I),delete e[g]);else{var g=[],h;for(h in e)pc(e[h].view,b,c)&&g.push(h);for(h=0;h<g.length;h++)foundQueryId=g[h],e[foundQueryId]&&!(0<e[foundQueryId].view.ca.length)&&(e[foundQueryId].I&&("default"===foundQueryId&&Cc(this,d,e[foundQueryId].view.Ba),e[foundQueryId].I(),delete e[foundQueryId].I),delete e[foundQueryId])}}};
function Dc(a,b,c){Ia(K(a.Fa,b),function(a){if(a=a.j())for(var b in a)sc(a[b].view)},c,k)}
Ac.prototype.ha=function(a,b){var c=this,d=this.bc,e=this.g.Ea;this.bc=e;1===arguments.length&&(b=k);var g=a.toString(),h=this.Fa,j=d.J(a),l=e.J(a),h=new uc(h,function(a,d,e){a.toString().substring(0,g.length)===g?(b&&Dc(c,a,n),c.ob(a,d,e),b&&Dc(c,a,k)):c.ob(a,d,e)}),w=vc(h,a,j,l),l=j.i()!==l.i();if(w||l)for(j=a;j.parent()!==m;){var u=d.J(j),I=e.J(j),q=j.parent();if(K(h.Pb,q).j()){var v=e.J(q),r=[],j=j.O<j.k.length?j.k[j.k.length-1]:m;if(u.e())u=v.Q(j,I),r.push(new W("child_added",I,j,u));else if(I.e())r.push(new W("child_removed",
u,j));else if(w&&(u=v.Q(j,I),r.push(new W("child_changed",I,j,u))),l)u=v.Q(j,I),r.push(new W("child_moved",I,j,u)),w=k;h.dc(q,v,r)}j=q;l=n}b&&Dc(this,a,k)};Ac.prototype.ob=function(a,b,c){a=K(this.Fa,a).j();if(a!==m)for(var d in a)a[d].view.ob(b,c)};function Cc(a,b,c){b.D(function(b){var e=b.j();if(e&&"default"in e)M(!e["default"].I),e["default"].I=Bc(a,e["default"].view.z);else{if(e)for(var g in e)M(!e[g].I),e[g].I=Bc(a,e[g].view.z);Cc(a,b,c)}})}
function Bc(a,b){if(a.w){var c=b.path.toString(),d=a.w,e=Ca(b),g=function(d){"ok"!==d&&(Cb("on() or once() for "+c+" failed: "+d),a.Ta(b))},h=Da(e);d.U[c]=d.U[c]||{};M(!d.U[c][h],"listen() called twice for same path/queryId.");d.U[c][h]={Ec:e,H:g};d.W&&ac(d,c,e,g);return z(a.w.Mc,a.w,c,Ca(b))}return aa};function Ec(a){this.F=a;this.w=new T(this.F,z(this.ib,this),z(this.Ac,this),z(this.Bc,this));this.ub=new Ga;this.g=new gc;this.aa=new Ac(this.w,this.g.la);this.Yb=new fc;this.Bb=new Ac(m,this.Yb);Fc(this,n)}s=Ec.prototype;s.toString=function(){return(this.F.Hb?"https://":"http://")+this.F.host};s.name=function(){return this.F.La};
s.ib=function(a,b,c){if(9<=a.length&&a.lastIndexOf(".priority")===a.length-9)a=new H(a.substring(0,a.length-9)),b!==m&&Ba.test(b)&&(b=Number(b)),c=U(this.g.Wa,a).xb(b);else if(c){var a=new H(a),c=U(this.g.Wa,a),d;for(d in b)var e=Q(b[d]),c=c.A(d,e)}else a=new H(a),c=Q(b);b=this.g;d=a;V(b.Wa,d,c);hc(b,d)&&(a=Gc(this,a),Hc(this,a),a=a.path());this.aa.ha(a)};s.Ac=function(){Fc(this,k)};s.Bc=function(){Fc(this,n)};function Fc(a,b){var c=new H("/.info/connected");V(a.Yb,c,Q(b));a.Bb.ha(c)}
s.Ga=function(a,b){this.w.Ga(a,b)};s.Za=function(){this.w.Za()};s.tb=function(a,b,c,d){c!==m&&Ba.test(c)&&(c=Number(c));this.c("set",{path:a.toString(),value:b});var b=Q(b,c),e=this.g.set(a,b),g=this;this.w.put(a.toString(),b.T(k),function(b){var c="ok"===b;jc(g.g,a,e);c||(Cb("set at "+a+" failed: "+b),hc(g.g,a),b=Gc(g,a),Hc(g,b),g.aa.ha(b.path(),n));d&&d(c)});b=Gc(this,a);Ic(this,a);Hc(this,b);this.aa.ha(b.path())};
s.update=function(a,b,c){this.c("update",{path:a.toString(),value:b});var d=U(this.g.la,a),e=k,g;for(g in b)var e=n,h=Q(b[g]),d=d.A(g,h);if(e)zb("update() called with empty data.  Don't do anything."),c&&c(k);else{var j=this.g.set(a,d),l=this;dc(this.w,"m",a.toString(),b,function(b){b="ok"===b;M(b,"merge at "+a+" failed.");jc(l.g,a,j);c&&c(b)},i);b=Gc(this,a);Ic(this,a);Hc(this,b);this.aa.ha(b.path())}};
s.Jb=function(a,b,c){this.c("setPriority",{path:a.toString(),ga:b});var d=U(this.g.R,a).xb(b),e=this.g.set(a,d),g=this;this.w.put(a.toString()+"/.priority",b,function(b){b="ok"===b;jc(g.g,a,e);c&&c(b)});b=Gc(this,a);Hc(this,b);this.aa.ha(b.path())};s.sb=function(a,b){this.w.Ma(a.toString(),b)};s.ab=function(a,b,c){".info"===F(a.path)?this.Bb.ab(a,b,c):this.aa.ab(a,b,c)};s.Ta=function(a,b,c){".info"===F(a.path)?this.Bb.Ta(a,b,c):this.aa.Ta(a,b,c)};s.Aa=function(){this.w.Aa()};s.Ua=function(){this.w.Ua()};
s.c=function(){zb("r:"+this.w.id+":",arguments)};function Jc(a,b){var c=new X(a,b);return new R(U(a.g.la,b),c)};function Ic(a,b){var c=K(a.ub,b);Ja(c,function(b){Kc(a,b)});Kc(a,c);Ia(c,function(b){Kc(a,b)})}function Kc(a,b){var c=b.j();if(c!==m){for(var d=-1,e=[],g=0;g<c.length;g++)if(2===c[g].status)M(d===g-1,"All SENT items should be at beginning of queue."),d=g,c[g].status=4,c[g].Mb="set";else if(c[g].wb(),c[g].H){var h=Jc(a,b.path());e.push(z(c[g].H,m,n,h))}-1===d?L(b,m):c.length=d+1;for(g=0;g<e.length;g++)e[g]()}}
function Lc(a,b){var c=b||a.ub;b||Mc(a,c);if(!c.e())if(c.j()!==m){var d=Nc(a,c);if(0!==d.length){var e=c.path();if(2!==d[0].status&&4!==d[0].status){for(var g=0;g<d.length;g++)M(1===d[g].status,"tryToSendTransactionForNode_: items in queue should all be run."),d[g].status=2,d[g].jc++;var h=U(a.g.R,e).hash();V(a.g.R,e,U(a.g.la,e));var j=U(a.g.R,e).T(k),l=ub();L(K(a.g.Qa,e),l);a.w.put(e.toString(),j,function(b){a.c("transaction put response",{path:e.toString(),status:b});var h=K(a.g.Qa,e),j=h.j();M(j!==
m,"tryToSendTransactionsForNode_: pendingPut should not be null.");j===l&&(L(h,m),V(a.g.R,e,U(a.g.Wa,e)));if("ok"===b){b=[];for(g=0;g<d.length;g++)d[g].status=3,d[g].H&&(h=Jc(a,d[g].path),b.push(z(d[g].H,m,k,h))),d[g].wb();Mc(a,c);Lc(a);for(g=0;g<b.length;g++)b[g]()}else{if("datastale"===b)for(g=0;g<d.length;g++)d[g].status=4===d[g].status?5:1;else{Cb("transaction at "+e+" failed: "+b);for(g=0;g<d.length;g++)d[g].status=5,d[g].Mb=b}b=Gc(a,e);Hc(a,b);a.aa.ha(b.path())}},h)}}}else c.D(function(b){Lc(a,
b)})}
function Hc(a,b){var c=b.path();V(a.g.la,c,U(a.g.R,c));var d=Nc(a,b);if(0!==d.length){for(var e=U(a.g.la,c),g=[],h=0;h<d.length;h++){var j=Ea(c,d[h].path),l=n,w;M(j!==m,"rerunTransactionsUnderNode_: relativePath should not be null.");if(5===d[h].status)l=k,w=d[h].Mb;else if(1===d[h].status)if(25<=d[h].jc)l=k,w="maxretry";else{var u=d[h].update(e.J(j).T());x(u)?(va("transaction failed: Data returned ",u),e=e.$a(j,Q(u))):(l=k,w="nodata")}l&&(d[h].wb(),d[h].status=3,d[h].H&&(l=new X(a,d[h].path),j=new R(e.J(j),
l),g.push(z(d[h].H,m,n,j,w))))}d=U(a.g.R,c).i();V(a.g.la,c,e.xb(d));Lc(a);for(h=0;h<g.length;h++)g[h]()}}function Gc(a,b){for(var c,d=a.ub;(c=F(b))!==m&&d.j()===m;)d=K(d,c),b=J(b);return d}function Nc(a,b){var c=[];Oc(a,b,c);c.sort(function(a,b){return a.fc-b.fc});return c}function Oc(a,b,c){var d=b.j();if(d!==m)for(var e=0;e<d.length;e++)c.push(d[e]);b.D(function(b){Oc(a,b,c)})}
function Mc(a,b){var c=b.j();if(c){for(var d=0,e=0;e<c.length;e++)3!==c[e].status&&(c[d]=c[e],d++);c.length=d;L(b,0<c.length?c:m)}b.D(function(b){Mc(a,b)})};function Y(){this.ra={}}Y.Wb=function(){return Y.Zb?Y.Zb:Y.Zb=new Y};Y.prototype.Aa=function(){for(var a in this.ra)this.ra[a].Aa()};Y.prototype.interrupt=Y.prototype.Aa;Y.prototype.Ua=function(){for(var a in this.ra)this.ra[a].Ua()};Y.prototype.resume=Y.prototype.Ua;var Z={Ic:function(){return Y.Wb().ra}};Z.repos=Z.Ic;Z.xc=function(a){var b=P.prototype.hash;P.prototype.hash=a;return function(){P.prototype.hash=b}};Z.hijackHash=Z.xc;Z.qa=function(a){return a.qa()};Z.queryIdentifier=Z.qa;Z.zc=function(a){return a.n.w.U};Z.listens=Z.zc;Z.Gc=function(a){return a.n.w.Sa};Z.refConnection=Z.Gc;Z.pc=T;Z.DataConnection=Z.pc;T.prototype.sendRequest=T.prototype.ta;T.prototype.interrupt=T.prototype.Aa;Z.qc=S;Z.RealTimeConnection=Z.qc;S.prototype.sendRequest=S.prototype.Ib;
S.prototype.close=S.prototype.close;Z.oc=db;Z.ConnectionTarget=Z.oc;Z.vc=function(){Ob=k;Lb.Nc.Oc()};Z.forceLongPolling=Z.vc;var Pc,Qc=0,Rc=[];Pc=function(){var a=(new Date).getTime()+Gb,b=a===Qc;Qc=a;for(var c=Array(8),d=7;0<=d;d--)c[d]="-0123456789ABCDEFGHIJKLMNOPQRSTUVWXYZ_abcdefghijklmnopqrstuvwxyz".charAt(a%64),a=Math.floor(a/64);M(0===a);a=c.join("");if(b){for(d=11;0<=d&&63===Rc[d];d--)Rc[d]=0;Rc[d]++}else for(d=0;12>d;d++)Rc[d]=Math.floor(64*Math.random());for(d=0;12>d;d++)a+="-0123456789ABCDEFGHIJKLMNOPQRSTUVWXYZ_abcdefghijklmnopqrstuvwxyz".charAt(Rc[d]);M(20===a.length,"NextPushId: Length should be 20.");return a};function X(){var a,b,c;if(arguments[0]instanceof Ec)c=arguments[0],a=arguments[1];else{A("new Firebase",1,2,arguments.length);a=arguments[0];var d="",e="",g=k;b="";if(y(a)){d=a.indexOf("//");0<=d&&(g="http:"!==a.substring(0,d),a=a.substring(d+2));var h=a.indexOf("/");-1===h&&(h=a.length);d=a.substring(0,h);a=a.substring(h+1);var h=a.indexOf("/"),j=d.split(".");3==j.length?("firebase"===j[1]?(Cb(d+" is deprecated. Please use <YOUR FIREBASE>.firebaseio.com instead"),0<h?(e=a.substring(0,h),b=Db(a.substring(h))):
(e=a,b="/"),j[0]=e,j[1]="firebaseio",d=j.join(".")):(e=j[0],b=Db("/"+a)),e=e.toLowerCase()):e=m}g||"undefined"!==typeof window&&(window.location&&window.location.protocol&&-1!==window.location.protocol.indexOf("https:"))&&Cb("Insecure Firebase access from a secure page. Please use https in calls to new Firebase().");a=new db(d,g,e);b=new H(b);g=b.toString();if(!(d=!y(a.host)))if(!(d=0===a.host.length))if(!(d=!ta(a.La)))if(d=0!==g.length)g&&(g=g.replace(/^\/*\.info(\/|$)/,"/")),d=!(y(g)&&0!==g.length&&
!sa.test(g));d&&f(Error(C("new Firebase",1,n)+'must be a valid firebase URL and the path can\'t contain ".", "#", "$", "[", or "]".'));arguments[1]?arguments[1]instanceof Y?c=arguments[1]:f(Error("Expected a valid Firebase.Context for second argument to new Firebase()")):c=Y.Wb();g=(a.Hb?"https://":"http://")+a.host;d=c.ra[g];d||(d=new Ec(a),c.ra[g]=d);c=d;a=b}G.call(this,c,a)}ha(X,G);var Sc=X,Tc=["Firebase"],$=t;!(Tc[0]in $)&&$.execScript&&$.execScript("var "+Tc[0]);
for(var Vc;Tc.length&&(Vc=Tc.shift());)!Tc.length&&x(Sc)?$[Vc]=Sc:$=$[Vc]?$[Vc]:$[Vc]={};X.prototype.name=function(){A("Firebase.name",0,0,arguments.length);return this.path.e()?this.n.name():this.path.O<this.path.k.length?this.path.k[this.path.k.length-1]:m};X.prototype.name=X.prototype.name;
X.prototype.G=function(a){A("Firebase.child",1,1,arguments.length);if(da(a))a=String(a);else if(!(a instanceof H))if(F(this.path)===m){var b=a;b&&(b=b.replace(/^\/*\.info(\/|$)/,"/"));Aa("Firebase.child",b)}else Aa("Firebase.child",a);return new X(this.n,this.path.G(a))};X.prototype.child=X.prototype.G;X.prototype.parent=function(){A("Firebase.parent",0,0,arguments.length);var a=this.path.parent();return a===m?m:new X(this.n,a)};X.prototype.parent=X.prototype.parent;
X.prototype.toString=function(){A("Firebase.toString",0,0,arguments.length);var a;if(this.parent()===m)a=this.n.toString();else{a=this.parent().toString()+"/";var b=this.name();a+=encodeURIComponent(String(b))}return a};X.prototype.toString=X.prototype.toString;X.prototype.set=function(a,b){A("Firebase.set",1,2,arguments.length);E("Firebase.set",this.path);ua("Firebase.set",a,n);D("Firebase.set",2,b,k);return this.n.tb(this.path,a,m,b)};X.prototype.set=X.prototype.set;
X.prototype.update=function(a,b){A("Firebase.update",1,2,arguments.length);E("Firebase.update",this.path);ea(a)||f(Error(C("Firebase.update",1,n)+" must be an object containing the children to replace."));ua("Firebase.update",a,n);D("Firebase.update",2,b,k);return this.n.update(this.path,a,b)};X.prototype.update=X.prototype.update;
X.prototype.tb=function(a,b,c){A("Firebase.setWithPriority",2,3,arguments.length);E("Firebase.setWithPriority",this.path);ua("Firebase.setWithPriority",a,n);wa("Firebase.setWithPriority",2,b,n);D("Firebase.setWithPriority",3,c,k);(".length"===this.name()||".keys"===this.name())&&f("Firebase.setWithPriority failed: "+this.name()+" is a read-only object.");return this.n.tb(this.path,a,b,c)};X.prototype.setWithPriority=X.prototype.tb;
X.prototype.remove=function(a){A("Firebase.remove",0,1,arguments.length);E("Firebase.remove",this.path);D("Firebase.remove",1,a,k);this.set(m,a)};X.prototype.remove=X.prototype.remove;
X.prototype.transaction=function(a,b){function c(){}A("Firebase.transaction",1,2,arguments.length);E("Firebase.transaction",this.path);D("Firebase.transaction",1,a,n);D("Firebase.transaction",2,b,k);(".length"===this.name()||".keys"===this.name())&&f("Firebase.transaction failed: "+this.name()+" is a read-only object.");var d=this.n,e=this.path;d.c("transaction on "+e);var g=new X(d,e);g.Db("value",c);var h={path:e,update:a,H:b,fc:ub(),jc:0,wb:function(){g.Cb("value",c)}},j=d.g.la,l=h.update(U(j,
e).T());if(x(l)){va("transaction failed: Data returned ",l);var w=U(d.g.R,e).i();V(j,e,Q(l,w));d.aa.ha(e);h.status=1;e=K(d.ub,e);j=e.j()||[];j.push(h);L(e,j);Lc(d)}else h.wb(),h.H&&(d=Jc(d,e),h.H(n,d))};X.prototype.transaction=X.prototype.transaction;X.prototype.Jb=function(a,b){A("Firebase.setPriority",1,2,arguments.length);E("Firebase.setPriority",this.path);wa("Firebase.setPriority",1,a,n);D("Firebase.setPriority",2,b,k);a!==m&&Ba.test(a)&&(a=Number(a));this.n.Jb(this.path,a,b)};
X.prototype.setPriority=X.prototype.Jb;X.prototype.push=function(a,b){A("Firebase.push",0,2,arguments.length);E("Firebase.push",this.path);ua("Firebase.push",a,k);D("Firebase.push",2,b,k);var c=Pc(),c=this.G(c);"undefined"!==typeof a&&a!==m&&c.set(a,b);return c};X.prototype.push=X.prototype.push;X.prototype.Hc=function(){A("Firebase.removeOnDisconnect",0,0,arguments.length);this.n.sb(this.path,m)};X.prototype.removeOnDisconnect=X.prototype.Hc;
X.prototype.sb=function(a){A("Firebase.setOnDisconnect",1,1,arguments.length);ua("Firebase.setOnDisconnect",a,n);this.n.sb(this.path,a)};X.prototype.setOnDisconnect=X.prototype.sb;X.prototype.Ga=function(a,b){A("Firebase.auth",1,2,arguments.length);y(a)||f(Error(C("Firebase.auth",1,n)+"must be a valid credential (a string)."));D("Firebase.auth",2,b,k);this.n.Ga(a,b)};X.prototype.auth=X.prototype.Ga;X.prototype.Za=function(){this.n.Za()};X.prototype.unauth=X.prototype.Za;
X.enableLogging=function(a){a===k?"undefined"!==typeof console&&("function"===typeof console.log?yb=z(console.log,console):"object"===typeof console.log&&(yb=function(a){console.log(a)})):yb=a?a:m};X.TEST_HOOKS=Z;X.Context=Y;})();
