// Generated by CoffeeScript 1.4.0
(function() {

  $(function() {
    console.log('oh hai there');
    chrome.extension.sendRequest({
      action: 'getState'
    }, function(response) {
      return $('#state').prop('checked', response.state || false);
    });
    return $('#state').click(function() {
      console.log('clicked');
      return chrome.extension.sendRequest({
        action: 'setState',
        state: $('#state').is(':checked')
      }, function(response) {
        return console.log(response);
      });
    });
  });

}).call(this);
